
spring:
  datasource:
    url: jdbc:mysql://localhost:3303/talizin_store
    username: root
    password: 92470
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 443
  error:
    include-binding-errors: ON_PARAM